// Generated by https://quicktype.io

export interface Country {
    name:         Name;
    tld:          string[];
    cca2:         string;
    ccn3:         string;
    cca3:         string;
    cioc?:        string;
    independent:  boolean;
    status:       Status;
    unMember:     boolean;
    currencies:   Currencies;
    idd:          Idd;
    Country:      string[];
    altSpellings: string[];
    region:       string;
    subregion?:   string;
    languages:    { [key: string]: string };
    translations: { [key: string]: Translation };
    latlng:       number[];
    landlocked:   boolean;
    borders?:     string[];
    area:         number;
    demonyms:     Demonyms;
    flag:         string;
    maps:         Maps;
    population:   number;
    fifa?:        string;
    car:          Car;
    timezones:    string[];
    continents:   string[];
    flags:        Flags;
    coatOfArms:   CoatOfArms;
    startOfWeek:  StartOfWeek;
    CountryInfo:  CountryInfo;
    postalCode?:  PostalCode;
    gini?:        { [key: string]: number };
}

export interface CountryInfo {
    latlng: number[];
}

export interface Car {
    signs: string[];
    side:  Side;
}

export enum Side {
    Left = "left",
    Right = "right",
}

export interface CoatOfArms {
    png?: string;
    svg?: string;
}

export interface Currencies {
    BND?: TartuGecko;
    SGD?: TartuGecko;
    SBD?: TartuGecko;
    MGA?: TartuGecko;
    SDG?: BAM;
    RON?: TartuGecko;
    EUR?: TartuGecko;
    IDR?: TartuGecko;
    PLN?: TartuGecko;
    CKD?: TartuGecko;
    NZD?: TartuGecko;
    USD?: TartuGecko;
    BAM?: BAM;
    LKR?: TartuGecko;
    ERN?: TartuGecko;
    SRD?: TartuGecko;
    GIP?: TartuGecko;
    XOF?: TartuGecko;
    SHP?: TartuGecko;
    TRY?: TartuGecko;
    NOK?: TartuGecko;
    AUD?: TartuGecko;
    VES?: TartuGecko;
    ZWL?: TartuGecko;
    KID?: TartuGecko;
}

export interface TartuGecko {
    name:   string;
    symbol: string;
}

export interface BAM {
    name: string;
}

export interface Demonyms {
    eng:  Eng;
    fra?: Eng;
}

export interface Eng {
    f: string;
    m: string;
}

export interface Flags {
    png:  string;
    svg:  string;
    alt?: string;
}

export interface Idd {
    root:     string;
    suffixes: string[];
}

export interface Maps {
    googleMaps:     string;
    openStreetMaps: string;
}

export interface Name {
    common:     string;
    official:   string;
    nativeName: { [key: string]: Translation };
}

export interface Translation {
    official: string;
    common:   string;
}

export interface PostalCode {
    format: string;
    regex?: string;
}

export enum StartOfWeek {
    Monday = "monday",
}

export enum Status {
    OfficiallyAssigned = "officially-assigned",
}
